import { Navbar } from "@/components/layout/Navbar";
import { AuthProvider } from "@/features/auth/components/AuthProvider";
import { authenticateUser } from "@/features/auth/services/authenticateUser";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Spotify Song Saver",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const isAuthenticated = await authenticateUser();

    return (
        <html lang="en">
            <AuthProvider initialAuth={isAuthenticated}>
                <body
                    className={`bg-neutral-900 antialiased flex min-h-screen items-center justify-center text-white`}
                >
                    <Navbar />
                    {children}
                </body>
            </AuthProvider>
        </html>
    );
}
