import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Spotify Song Saver",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`bg-black antialiased flex min-h-screen items-center justify-center text-white`}
            >
                {children}
            </body>
        </html>
    );
}
