import { Navbar } from "@/components/layout/Navbar";
import { AuthProvider } from "@/features/auth/components/AuthProvider";
import { getAuthStatus } from "@/features/auth/services/getAuthStatus";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Spotify Song Saver",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const auth = await getAuthStatus();
    console.log("ello" + auth.isAuthenticated);

    return (
        <html lang="en">
            <AuthProvider initialAuth={auth}>
                <body
                    className={`bg-neutral-900 antialiased flex min-h-screen items-center justify-center text-white flex-col overflow-hidden"`}
                >
                    <Navbar />
                    {children}
                </body>
            </AuthProvider>
        </html>
    );
}
